version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "4000:2000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
